<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    use WithoutModelEvents;

    public function run(): void
    {
        DB::table('categories')->insert([
            ['id' => 1, 'name' => 'TVs', 'slug' => 'tvs', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 2, 'name' => 'Smartphones', 'slug' => 'smartphones', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 3, 'name' => 'Laptops', 'slug' => 'laptops', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 4, 'name' => 'Audio', 'slug' => 'audio', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 5, 'name' => 'Wearables', 'slug' => 'wearables', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 6, 'name' => 'Accessories', 'slug' => 'accessories', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 7, 'name' => 'Gaming', 'slug' => 'gaming', 'created_at' => now(), 'updated_at' => now()],
        ]);

        DB::table('brands')->insert([
            ['id' => 1, 'name' => 'Samsung', 'slug' => 'samsung', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 2, 'name' => 'LG', 'slug' => 'lg', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 3, 'name' => 'Apple', 'slug' => 'apple', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 4, 'name' => 'Dell', 'slug' => 'dell', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 5, 'name' => 'Sony', 'slug' => 'sony', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 6, 'name' => 'Bose', 'slug' => 'bose', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 7, 'name' => 'Anker', 'slug' => 'anker', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 8, 'name' => 'Logitech', 'slug' => 'logitech', 'created_at' => now(), 'updated_at' => now()],
        ]);

        DB::table('products')->insert([
            [
                'id' => 1,
                'name' => 'GalaxyVision 55" 4K UHD Smart TV',
                'slug' => 'galaxyvision-55-4k-uhd-smart-tv',
                'category_id' => 1,
                'brand_id' => 1,
                'price' => 699.99,
                'image' => 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=600&h=450&fit=crop&q=80&auto=format',
                'alt' => 'GalaxyVision 55 inch flat screen smart television',
                'description' => 'Crisp 4K UHD picture with HDR10+ and a built-in smart hub for all your streaming apps. Slim bezels look great in any room.',
                'features' => json_encode(['55" 4K UHD HDR10+ panel', 'Smart hub with voice control', '4× HDMI 2.1 ports', 'Ambient light sensor']),
                'stock' => 12,
                'rating' => 4.6,
                'reviews' => 1284,
                'is_active' => true,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'name' => 'Aurora 65" OLED 4K TV',
                'slug' => 'aurora-65-oled-4k-tv',
                'category_id' => 1,
                'brand_id' => 2,
                'price' => 1499.99,
                'image' => 'https://images.unsplash.com/photo-1461151304267-38535e780c79?w=600&h=450&fit=crop&q=80&auto=format',
                'alt' => 'Aurora 65 inch OLED television with ultra-thin screen',
                'description' => 'Self-lit OLED pixels deliver perfect blacks and stunning contrast. Ideal for movies, gaming and sports.',
                'features' => json_encode(['65" OLED 4K panel', '120Hz refresh rate', 'Dolby Vision & Atmos', 'Game optimizer mode']),
                'stock' => 3,
                'rating' => 4.8,
                'reviews' => 862,
                'is_active' => true,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'name' => 'Nova X1 5G Smartphone',
                'slug' => 'nova-x1-5g-smartphone',
                'category_id' => 2,
                'brand_id' => 1,
                'price' => 899.99,
                'image' => 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&h=450&fit=crop&q=80&auto=format',
                'alt' => 'Nova X1 smartphone with edge-to-edge display',
                'description' => 'Flagship 5G performance with a 6.4" AMOLED display, 108MP triple camera and all-day battery.',
                'features' => json_encode(['6.4" AMOLED 120Hz', '108MP triple camera', '5G + Wi-Fi 6', '5,000 mAh battery']),
                'stock' => 18,
                'rating' => 4.5,
                'reviews' => 2310,
                'is_active' => true,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'name' => 'PixelBloom 15 Pro Smartphone',
                'slug' => 'pixelbloom-15-pro-smartphone',
                'category_id' => 2,
                'brand_id' => 3,
                'price' => 1099.99,
                'image' => 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=600&h=450&fit=crop&q=80&auto=format',
                'alt' => 'PixelBloom 15 Pro smartphone in titanium finish',
                'description' => 'Pro-grade camera system with 48MP main sensor, A17-class chip and a stunning always-on display.',
                'features' => json_encode(['6.7" ProMotion display', '48MP pro camera system', 'Titanium frame', 'USB-C fast charge']),
                'stock' => 20,
                'rating' => 4.9,
                'reviews' => 4107,
                'is_active' => true,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'name' => 'SwiftBook 14 Ultrabook',
                'slug' => 'swiftbook-14-ultrabook',
                'category_id' => 3,
                'brand_id' => 4,
                'price' => 1199.99,
                'image' => 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=600&h=450&fit=crop&q=80&auto=format',
                'alt' => 'SwiftBook 14 ultrabook open on a desk',
                'description' => 'Feather-light 14" ultrabook with 16GB RAM, 512GB SSD and 18 hours of battery for work on the move.',
                'features' => json_encode(['14" 2.5K IPS display', 'Intel Core i7 / 16GB RAM', '512GB NVMe SSD', '18-hour battery']),
                'stock' => 8,
                'rating' => 4.4,
                'reviews' => 976,
                'is_active' => true,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'name' => 'Titan Pro 16 Gaming Laptop',
                'slug' => 'titan-pro-16-gaming-laptop',
                'category_id' => 3,
                'brand_id' => 4,
                'price' => 1899.99,
                'image' => 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=600&h=450&fit=crop&q=80&auto=format',
                'alt' => 'Titan Pro 16 gaming laptop with RGB keyboard',
                'description' => 'Desktop-class RTX graphics, 165Hz display and advanced cooling for serious gaming and creative work.',
                'features' => json_encode(['16" 165Hz QHD display', 'RTX 4070 GPU', '32GB DDR5 RAM', '1TB SSD storage']),
                'stock' => 0,
                'rating' => 4.7,
                'reviews' => 543,
                'is_active' => true,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'name' => 'AirWave Wireless Earbuds',
                'slug' => 'airwave-wireless-earbuds',
                'category_id' => 4,
                'brand_id' => 5,
                'price' => 129.99,
                'image' => 'https://images.unsplash.com/photo-1572569511254-d8f925fe2cbb?w=600&h=450&fit=crop&q=80&auto=format',
                'alt' => 'AirWave wireless earbuds with charging case',
                'description' => 'True wireless earbuds with active noise cancellation, 30-hour total battery and crystal-clear calls.',
                'features' => json_encode(['Active noise cancelling', '30h battery with case', 'IPX4 water resistant', 'Touch controls']),
                'stock' => 25,
                'rating' => 4.3,
                'reviews' => 1893,
                'is_active' => true,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'name' => 'StudioMax Over-Ear Headphones',
                'slug' => 'studiomax-over-ear-headphones',
                'category_id' => 4,
                'brand_id' => 6,
                'price' => 349.99,
                'image' => 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&h=450&fit=crop&q=80&auto=format',
                'alt' => 'StudioMax over-ear headphones in black',
                'description' => 'Award-winning comfort and adaptive noise cancelling for immersive studio-grade sound anywhere.',
                'features' => json_encode(['Adaptive noise cancelling', '40h wireless battery', 'Hi-Fi acoustics', 'Multipoint pairing']),
                'stock' => 10,
                'rating' => 4.6,
                'reviews' => 1120,
                'is_active' => true,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'name' => 'BoomPort Bluetooth Speaker',
                'slug' => 'boomport-bluetooth-speaker',
                'category_id' => 4,
                'brand_id' => 5,
                'price' => 89.99,
                'image' => 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600&h=450&fit=crop&q=80&auto=format',
                'alt' => 'BoomPort portable bluetooth speaker',
                'description' => 'Rugged portable speaker with 360° sound, deep bass and 12-hour playtime. Take the party anywhere.',
                'features' => json_encode(['360° sound', '12h playtime', 'Water & dust proof', 'Speakerphone built-in']),
                'stock' => 0,
                'rating' => 4.2,
                'reviews' => 740,
                'is_active' => true,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'name' => 'TitanWatch S2 Smartwatch',
                'slug' => 'titanwatch-s2-smartwatch',
                'category_id' => 5,
                'brand_id' => 1,
                'price' => 249.99,
                'image' => 'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=600&h=450&fit=crop&q=80&auto=format',
                'alt' => 'TitanWatch S2 smartwatch with health tracking',
                'description' => 'Track workouts, heart rate and sleep with precision. AMOLED display and 7-day battery life.',
                'features' => json_encode(['AMOLED always-on display', 'Heart rate & sleep tracking', 'GPS built-in', '7-day battery']),
                'stock' => 15,
                'rating' => 4.1,
                'reviews' => 658,
                'is_active' => true,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'name' => 'QuickCharge 65W USB-C Adapter',
                'slug' => 'quickcharge-65w-usb-c-adapter',
                'category_id' => 6,
                'brand_id' => 7,
                'price' => 39.99,
                'image' => 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=600&h=450&fit=crop&q=80&auto=format',
                'alt' => 'QuickCharge 65W USB-C wall adapter with two ports',
                'description' => 'Charge a laptop and phone at once with 65W fast charging and GaN technology in a pocket-size body.',
                'features' => json_encode(['65W GaN fast charging', '2× USB-C + 1× USB-A', 'Safety temperature control', 'Universal compatibility']),
                'stock' => 40,
                'rating' => 4.4,
                'reviews' => 3205,
                'is_active' => true,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'name' => 'NanoHue Wireless Mouse',
                'slug' => 'nanohue-wireless-mouse',
                'category_id' => 6,
                'brand_id' => 8,
                'price' => 59.99,
                'image' => 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600&h=450&fit=crop&q=80&auto=format',
                'alt' => 'NanoHue wireless mouse with silent clicks',
                'description' => 'Ultra-quiet clicks, silent scrolling and a sculpted shape. Connects to three devices at once.',
                'features' => json_encode(['Silent click & scroll', 'Triple-device pairing', '1,000 DPI sensor', '18-month battery']),
                'stock' => 30,
                'rating' => 4.5,
                'reviews' => 1520,
                'is_active' => true,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 13,
                'name' => 'PlayStation 5 Console',
                'slug' => 'playstation-5-console',
                'category_id' => 7,
                'brand_id' => 5,
                'price' => 499.99,
                'image' => 'https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=600&h=450&fit=crop&q=80&auto=format',
                'alt' => 'PlayStation 5 console standing upright',
                'description' => 'Next-gen gaming with lightning-fast SSD loading, ray tracing and the DualSense controller. Play the biggest exclusives in stunning 4K.',
                'features' => json_encode(['Custom AMD 8-core CPU', 'Ultra-fast 1TB SSD', 'Ray tracing support', '4K 120fps output']),
                'stock' => 7,
                'rating' => 4.9,
                'reviews' => 5120,
                'is_active' => true,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 14,
                'name' => 'DualSense Wireless Controller',
                'slug' => 'dualsense-wireless-controller',
                'category_id' => 7,
                'brand_id' => 5,
                'price' => 69.99,
                'image' => 'https://images.unsplash.com/photo-1605835963874-a7c87f56259e?w=600&h=450&fit=crop&q=80&auto=format',
                'alt' => 'White DualSense wireless controller for PlayStation 5',
                'description' => 'The official PlayStation 5 controller — feel the game with haptic feedback and adaptive triggers. Built-in mic, motion controls and a long-lasting battery.',
                'features' => json_encode(['Haptic feedback triggers', 'Adaptive triggers', 'Built-in microphone', 'USB-C rechargeable']),
                'stock' => 22,
                'rating' => 4.7,
                'reviews' => 3875,
                'is_active' => true,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        User::create([
            'name' => 'Site Admin',
            'email' => 'ali@dctech.example',
            'password' => Hash::make('admin123'),
            'is_admin' => true,
        ]);
    }
}
